package com.github.se.signify.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF05A9FB)
val md_theme_light_onPrimary = Color(0xFF000000)
val md_theme_light_secondary = Color(0xFFD32F2F)
val md_theme_light_onSecondary = Color(0xFF000000)
val md_theme_light_tertiary = Color(0xFF2E7D32)
val md_theme_light_onTertiary = Color(0xFF000000)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF000000)
val md_theme_light_surface = Color(0xFF333333)
val md_theme_light_onSurface = Color(0xFFFFFFFF)
val md_theme_light_inverseSurface = Color(0xFF05A9FB)
val md_theme_light_inverseOnSurface = Color(0xFFFFFFFF)
val md_theme_light_error = Color(0xFFD32F2F)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFE5B6B1)
val md_theme_light_onErrorContainer = Color(0xFFD32F2F)
val md_theme_light_outline = Color(0xFF000000)
val md_theme_light_outlineVariant = Color(0xFF05A9FB)

val md_theme_dark_primary = Color(0xFF05A9FB)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_secondary = Color(0xFFD32F2F)
val md_theme_dark_onSecondary = Color(0xFFFFFFFF)
val md_theme_dark_tertiary = Color(0xFF2E7D32)
val md_theme_dark_onTertiary = Color(0xFFFFFFFF)
val md_theme_dark_background = Color(0xFF333333)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF333333)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_inverseSurface = Color(0xFF05A9FB)
val md_theme_dark_inverseOnSurface = Color(0xFF000000)
val md_theme_dark_error = Color(0xFFD32F2F)
val md_theme_dark_onError = Color(0xFFFFFFFF)
val md_theme_dark_errorContainer = Color(0xFFE5B6B1)
val md_theme_dark_onErrorContainer = Color(0xFFD32F2F)
val md_theme_dark_outline = Color(0xFFFFFFFF)
val md_theme_dark_outlineVariant = Color(0xFF05A9FB)
